-- W1 reanalysis_genre UPDATE: reanalysis_sp 첫 문장에서 장르 추출
-- 생성: 2026-05-09, 대상: 326행
BEGIN;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop ballad' WHERE id = 60;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with jazz-pop and soul influences' WHERE id = 61;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 62;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 63;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Hip Hop with a boom bap influence' WHERE id = 64;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B track featuring a male vocalist' WHERE id = 65;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and synth-pop fusion featuring male vocals' WHERE id = 66;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 67;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and J-Pop fusion with elements of City Pop and Funk' WHERE id = 68;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with acoustic folk influences' WHERE id = 69;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie rock track featuring a clean electric guitar playing a rhythmic, syncopated chord pattern' WHERE id = 70;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop with a light funk influence' WHERE id = 71;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie pop with a mid-tempo groove' WHERE id = 72;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop, upbeat indie pop' WHERE id = 73;
UPDATE suno_reanalysis SET reanalysis_genre = 'Indie pop with a funk-influenced groove' WHERE id = 74;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 75;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad featuring a bright, fingerstyle acoustic guitar and a warm, melodic male vocal' WHERE id = 76;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Synth-pop' WHERE id = 77;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop, J-Rock, Pop Rock' WHERE id = 78;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocal' WHERE id = 79;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop, J-Pop, upbeat pop-rock' WHERE id = 80;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 81;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk pop' WHERE id = 82;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie R&B ballad' WHERE id = 83;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 84;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 85;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 86;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring a male rapper with a rhythmic, percussive delivery' WHERE id = 87;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 88;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with soft rock influences' WHERE id = 89;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie, Bossa Nova' WHERE id = 90;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Rock with high-energy punk influences' WHERE id = 91;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 92;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with elements of funk and disco' WHERE id = 93;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 94;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 95;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop with a laid-back jazz-rap influence' WHERE id = 96;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop' WHERE id = 97;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 98;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocal' WHERE id = 99;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Rock track featuring aggressive distorted electric guitars and driving live drums' WHERE id = 100;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 101;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop bubblegum pop track in G Major at 124 BPM' WHERE id = 102;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Ballad featuring a baritone male vocal' WHERE id = 103;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Synth-pop' WHERE id = 104;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie ballad' WHERE id = 105;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 106;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track at 90 BPM in the key of G Minor' WHERE id = 107;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Hip Hop track featuring a male rapper with a laid-back, rhythmic flow' WHERE id = 108;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 109;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 111;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 110;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Rock' WHERE id = 112;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 113;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with bubblegum pop and synth-pop influences' WHERE id = 114;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Ballad featuring a baritone male vocal' WHERE id = 115;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Future Bass fusion' WHERE id = 116;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie acoustic ballad' WHERE id = 117;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with soft rock influences' WHERE id = 118;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B track featuring a smooth male vocal performance' WHERE id = 119;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B with a mid-tempo groove' WHERE id = 121;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and J-Pop fusion with high-energy bubblegum pop elements' WHERE id = 120;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 122;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 124;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 123;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B track with a mid-tempo groove' WHERE id = 125;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Rock track featuring a male tenor vocal' WHERE id = 126;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 127;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 128;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and City Pop fusion' WHERE id = 129;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring a male rapper and a melodic male vocalist' WHERE id = 130;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Rock with heavy J-Rock influences' WHERE id = 131;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 132;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 133;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 134;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Bubblegum Pop' WHERE id = 135;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Korean Hip-Hop track featuring a male rapper and vocalist' WHERE id = 136;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track at 95 BPM in G Major' WHERE id = 137;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Rock track featuring distorted electric guitars, driving acoustic drums, and a male vocal lead' WHERE id = 138;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Punk with a high-energy pop-rock arrangement' WHERE id = 139;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B and Neo-Soul' WHERE id = 140;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 141;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop rock track featuring a male tenor vocalist' WHERE id = 142;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring a rhythmic piano loop playing syncopated jazz chords' WHERE id = 143;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Funk Pop' WHERE id = 144;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop dance-pop track featuring bright female vocals and heavy electronic production' WHERE id = 145;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 146;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 147;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie, Dream Pop' WHERE id = 148;
UPDATE suno_reanalysis SET reanalysis_genre = 'Korean Lo-fi Hip Hop' WHERE id = 149;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 150;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 151;
UPDATE suno_reanalysis SET reanalysis_genre = 'Pop-punk with high-gain distorted electric guitars and aggressive male vocals' WHERE id = 152;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring a male rapper and a melodic male vocalist' WHERE id = 153;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-pop dance-pop track in G major at 124 BPM' WHERE id = 154;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 155;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 156;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad featuring a male baritone vocalist' WHERE id = 157;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 158;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 159;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop rock ballad' WHERE id = 160;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie acoustic pop ballad' WHERE id = 161;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 162;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 163;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring a male rapper and melodic vocalist' WHERE id = 164;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop with a laid-back, acoustic-driven arrangement' WHERE id = 165;
UPDATE suno_reanalysis SET reanalysis_genre = 'Pop-punk with high-gain distorted electric guitars and driving acoustic drums' WHERE id = 166;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop funk-pop fusion' WHERE id = 167;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop' WHERE id = 168;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Synth-pop' WHERE id = 169;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 170;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Bossa Nova' WHERE id = 171;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 172;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop track in G Major at 100 BPM' WHERE id = 173;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop with R&B influences' WHERE id = 174;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 175;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 176;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with synth-pop elements' WHERE id = 177;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop rock track featuring distorted electric guitars and a driving drum kit' WHERE id = 178;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B with jazz-pop influences' WHERE id = 179;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 180;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Rock with high-gain electric guitars and driving percussion' WHERE id = 181;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 182;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop influenced Pop Rock' WHERE id = 183;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 184;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 185;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie, Jazz-Pop' WHERE id = 186;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 187;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie, Jazz-Pop' WHERE id = 188;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop with Jazz-Rap influences' WHERE id = 189;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with elements of funk and disco' WHERE id = 190;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with hip-hop elements' WHERE id = 191;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male tenor vocal' WHERE id = 192;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with acoustic pop elements' WHERE id = 193;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 194;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male tenor vocal' WHERE id = 195;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop, J-Pop, Funk Pop' WHERE id = 196;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocal' WHERE id = 197;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocal' WHERE id = 198;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 199;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with acoustic pop elements' WHERE id = 200;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male tenor vocal' WHERE id = 201;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocal' WHERE id = 202;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop' WHERE id = 203;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 204;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 205;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with City Pop influences' WHERE id = 206;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with synth-pop and funk influences' WHERE id = 207;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop, J-Rock, high-energy pop-rock' WHERE id = 208;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 209;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 210;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male tenor vocalist' WHERE id = 211;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 212;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 213;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop educational pop track' WHERE id = 214;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop educational pop track' WHERE id = 215;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop educational pop track' WHERE id = 216;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 217;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal with heavy plate reverb' WHERE id = 218;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Ballad featuring a baritone male vocal' WHERE id = 219;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop' WHERE id = 220;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B with a mid-tempo groove' WHERE id = 221;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and J-Rock fusion with elements of Funk Rock' WHERE id = 222;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring a blend of soulful R&B vocal hooks and rhythmic rap verses' WHERE id = 223;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 224;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 225;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop bubblegum pop track featuring bright, clean electric guitar strumming and a syncopated bassline' WHERE id = 226;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop track with elements of funk and bubblegum pop' WHERE id = 227;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 228;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 229;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 230;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 231;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocal' WHERE id = 232;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 233;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 234;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 235;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 236;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with synth-pop elements' WHERE id = 237;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with synth-pop elements' WHERE id = 238;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-pop ballad featuring a female vocalist' WHERE id = 239;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 240;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 241;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie pop track featuring a female vocalist with a breathy, intimate delivery' WHERE id = 242;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Lo-fi Pop' WHERE id = 243;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 244;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 245;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop track in G Major at 110 BPM' WHERE id = 246;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop' WHERE id = 247;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop indie pop ballad' WHERE id = 248;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Hip Hop with a smooth R&B influence' WHERE id = 249;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 250;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 251;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop, City Pop' WHERE id = 252;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 253;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop inspired Pop Rock' WHERE id = 254;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring a prominent funk-influenced electric bassline playing syncopated sixteenth-note patterns' WHERE id = 255;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 256;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 257;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 258;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B track with a laid-back groove' WHERE id = 259;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie acoustic pop' WHERE id = 260;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 261;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 262;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 263;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with jazz-pop influences' WHERE id = 264;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 265;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 266;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad featuring a male tenor vocalist' WHERE id = 267;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with jazz-pop influences' WHERE id = 268;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 269;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie pop with a lo-fi aesthetic' WHERE id = 270;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop musical theater hybrid' WHERE id = 271;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 272;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 273;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie ballad' WHERE id = 274;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie ballad' WHERE id = 275;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Synth-pop fusion' WHERE id = 276;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 277;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with elements of synth-pop and funk' WHERE id = 278;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Synth-pop fusion' WHERE id = 279;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad featuring fingerstyle acoustic guitar and soft male vocals' WHERE id = 280;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 281;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 282;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop track featuring a male tenor vocal' WHERE id = 283;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop track featuring a smooth male tenor vocal' WHERE id = 284;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B and Neo-Soul' WHERE id = 285;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocal' WHERE id = 286;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 287;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B with a mid-tempo groove' WHERE id = 288;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop synth-pop track in G Major at 118 BPM' WHERE id = 289;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a female vocalist' WHERE id = 290;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Ballad' WHERE id = 291;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk with a bright, polished production style' WHERE id = 292;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 293;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop rock with a driving punk influence' WHERE id = 294;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie pop with bossa nova influences' WHERE id = 295;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track at 95 BPM in G minor' WHERE id = 296;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 297;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie, Folk-Pop' WHERE id = 298;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with soft rock influences' WHERE id = 299;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Hip-Hop track featuring aggressive male rap vocals and a heavy trap-influenced beat' WHERE id = 300;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 301;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 302;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk with a heavy emphasis on slap bass and syncopated guitar scratching' WHERE id = 303;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Funk-Pop fusion' WHERE id = 304;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad' WHERE id = 305;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 306;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Hip Hop track featuring a male rapper' WHERE id = 307;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with synth-pop elements' WHERE id = 308;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Rock with pop-punk influences' WHERE id = 309;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 310;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with City Pop and Funk influences' WHERE id = 311;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop, Bubblegum Pop' WHERE id = 312;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-pop and synth-pop track in G major at 124 BPM' WHERE id = 313;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Synth-pop' WHERE id = 314;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk with a disco-influenced arrangement' WHERE id = 315;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop track at 115 BPM in E Major' WHERE id = 316;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male baritone vocalist' WHERE id = 317;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 318;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a baritone male vocal' WHERE id = 319;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 320;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 321;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with elements of synth-pop and funk' WHERE id = 322;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop' WHERE id = 323;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Funk-Pop' WHERE id = 324;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop' WHERE id = 325;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie Pop with a laid-back, jazzy R&B influence' WHERE id = 326;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad featuring a male and female vocal duet' WHERE id = 327;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie acoustic folk ballad' WHERE id = 328;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Rock track in E Major at 115 BPM' WHERE id = 329;
UPDATE suno_reanalysis SET reanalysis_genre = 'J-Rock and Pop-Punk fusion' WHERE id = 330;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 331;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop with City Pop influences' WHERE id = 332;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop inspired J-Rock with funk influences' WHERE id = 333;
UPDATE suno_reanalysis SET reanalysis_genre = 'Jazz trio ballad featuring a baritone male vocalist' WHERE id = 334;
UPDATE suno_reanalysis SET reanalysis_genre = 'J-Rock and Pop-Punk fusion' WHERE id = 335;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Rock with heavy metal influences' WHERE id = 336;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Rock track in E Major at 115 BPM' WHERE id = 337;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 338;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Rock with pop-punk influences' WHERE id = 339;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 340;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Jazz-Pop ballad' WHERE id = 341;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 342;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 343;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 344;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B track featuring a smooth male tenor vocal' WHERE id = 345;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and J-Rock fusion' WHERE id = 346;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie folk ballad' WHERE id = 347;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 348;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 349;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie ballad' WHERE id = 350;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 351;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and J-Rock fusion' WHERE id = 352;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Rock' WHERE id = 353;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 354;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie rock with elements of post-punk and dream pop' WHERE id = 355;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad with a mid-tempo groove' WHERE id = 356;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with acoustic folk influences' WHERE id = 357;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and City Pop fusion' WHERE id = 358;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop fusion' WHERE id = 359;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Punk' WHERE id = 360;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 361;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with R&B influences' WHERE id = 362;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop City Pop track in G Major at 115 BPM' WHERE id = 363;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Rock with a driving pop-punk influence' WHERE id = 364;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Indie Pop' WHERE id = 365;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad with soft rock influences' WHERE id = 366;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with elements of Nu-Disco and Funk' WHERE id = 367;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 368;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 369;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop and Bubblegum Pop' WHERE id = 370;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B ballad' WHERE id = 371;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a soft female vocal lead' WHERE id = 372;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie acoustic ballad' WHERE id = 373;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie acoustic ballad' WHERE id = 374;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie pop track featuring a clean electric guitar playing jazz-influenced seventh chords with a light chorus effect' WHERE id = 375;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie ballad' WHERE id = 376;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie ballad' WHERE id = 377;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop R&B with neo-soul influences' WHERE id = 378;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop acoustic ballad' WHERE id = 379;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop ballad featuring a male tenor vocal' WHERE id = 380;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop Rock with high-energy J-Rock influences' WHERE id = 381;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop rock with heavy punk influences' WHERE id = 382;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie pop ballad' WHERE id = 383;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Indie pop ballad' WHERE id = 384;
UPDATE suno_reanalysis SET reanalysis_genre = 'K-Pop with elements of funk and disco' WHERE id = 385;
COMMIT;
